version: 2.1

orbs:
  win: circleci/windows@1.0.0
  github-release: h-matsuo/github-release@0.1.3

jobs:
  build:
    description: Copying files.
    executor:
      name: win/vs2019
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: "Copying .cs files to the artifacts folder."
          command: xcopy ".\LazyContracts\*.cs" ".\Artifacts\" /c /i /q /y
      - run:
          name: "Copying .txt files to the artifacts folder."
          command: xcopy ".\LazyContracts\*.txt" ".\Artifacts\" /c /i /q /y
  release:
    description: Github Release.
    executor: github-release/default
    steps:
      - github-release/delete:
          tag: Latest
      - github-release/create:
          tag: Latest
          title: Latest Version
          description: This is the latest release.
          file-path: .\Artifacts\
workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - release:
          requires:
            - build